apiVersion: v1
kind: Service
metadata:
  name: zoo1
  labels:
    app: zookeeper-1
spec:
  type: NodePort
  ports:
  - name: client
    port: 2181
    targetPort: 2181
    nodePort: 30701
    protocol: TCP
  - name: follower
    port: 2888
    targetPort: 2888
    nodePort: 30702
    protocol: TCP
  - name: leader
    port: 3888
    targetPort: 3888
    nodePort: 30703
    protocol: TCP
  selector:
    app: zookeeper-1
---
apiVersion: v1
kind: Service
metadata:
  name: zoo2
  labels:
    app: zookeeper-2
spec:
  type: NodePort
  ports:
  - name: client
    port: 2181
    targetPort: 2181
    nodePort: 30704
    protocol: TCP
  - name: follower
    port: 2888
    targetPort: 2888
    nodePort: 30705
    protocol: TCP
  - name: leader
    port: 3888
    targetPort: 3888
    nodePort: 30706
    protocol: TCP
  selector:
    app: zookeeper-2
---
apiVersion: v1
kind: Service
metadata:
  name: zoo3
  labels:
    app: zookeeper-3
spec:
  type: NodePort
  ports:
  - name: client
    port: 2181
    targetPort: 2181
    nodePort: 30707
    protocol: TCP
  - name: follower
    port: 2888
    targetPort: 2888
    nodePort: 30708
    protocol: TCP
  - name: leader
    port: 3888
    targetPort: 3888
    nodePort: 30709
    protocol: TCP
  selector:
    app: zookeeper-3