apiVersion: v1
kind: Service
metadata:
  name: zoo1
  labels:
    app: zookeeper-1
spec:
  type: NodePort
  ports:
  - name: client
    port: 2181
    targetPort: 2181
    nodePort: 10907
    protocol: TCP
  - name: follower
    port: 2888
    targetPort: 2888
    nodePort: 10908
    protocol: TCP
  - name: leader
    port: 3888
    targetPort: 3888
    nodePort: 10909
    protocol: TCP
  selector:
    app: zookeeper-1
---
apiVersion: v1
kind: Service
metadata:
  name: zoo2
  labels:
    app: zookeeper-2
spec:
  type: NodePort
  ports:
  - name: client
    port: 2181
    targetPort: 2181
    nodePort: 20907
    protocol: TCP
  - name: follower
    port: 2888
    targetPort: 2888
    nodePort: 20908
    protocol: TCP
  - name: leader
    port: 3888
    targetPort: 3888
    nodePort: 20909
    protocol: TCP
  selector:
    app: zookeeper-2
---
apiVersion: v1
kind: Service
metadata:
  name: zoo3
  labels:
    app: zookeeper-3
spec:
  type: NodePort
  ports:
  - name: client
    port: 2181
    targetPort: 2181
    nodePort: 30907
    protocol: TCP
  - name: follower
    port: 2888
    targetPort: 2888
    nodePort: 30908
    protocol: TCP
  - name: leader
    port: 3888
    targetPort: 3888
    nodePort: 30909
    protocol: TCP
  selector:
    app: zookeeper-3